version: "3.7"
services:
  ropapi:
    hostname: ropapi
    container_name: riskofpainapi
    restart: always
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file: .env
    ports:
      - 9001:9001
